### ISSUE TITLE
output appears to be invalid for contract-call

### ISSUE THREAD

**Issue by donpdonp** [jcnelson/stacks-node-cli#1]
Making this contract call to the pox-2 address appears to be executed. The parameter to the function call comes from using `stacks-node-cli encode uint 11`

```
$ cat testnet.seed.txt|  ./wallet-cli contract-call -N "http://next.stacks.org:20443" -s - -t -f 123 -n 1 -v -A 1  ST000000000000000000002AMW42H.pox-2 get-total-ustx-stacked "1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11"
(node:925825) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
"128,128,0,0,0,4,0,50,54,87,196,32,32,230,150,78,39,81,15,24,153,178,224,198,207,36,107,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,123,0,1,171,191,100,129,58,63,164,19,151,7,176,35,174,206,1,180,150,47,212,176,218,137,187,142,11,200,88,141,150,77,50,38,83,225,246,192,141,175,237,199,67,56,234,228,66,40,234,173,248,102,56,233,94,209,174,212,64,98,71,173,50,101,202,191,3,2,0,0,0,0,2,26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,112,111,120,45,50,22,103,101,116,45,116,111,116,97,108,45,117,115,116,120,45,115,116,97,99,107,101,100,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,17"
```

when the output is given back to be decoded, I'm trying to find the return value from the function call,  an error is thrown during decode.
```
$ ./stacks-node-cli decode "128,128,0,0,0,4,0,50,54,87,196,32,32,230,150,78,39,81,15,24,153,178,224,198,207,36,107,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,123,0,1,171,191,100,129,58,63,164,19,151,7,176,35,174,206,1,180,150,47,212,176,218,137,187,142,11,200,88,141,150,77,50,38,83,225,246,192,141,175,237,199,67,56,234,228,66,40,234,173,248,102,56,233,94,209,174,212,64,98,71,173,50,101,202,191,3,2,0,0,0,0,2,26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,112,111,120,45,50,22,103,101,116,45,116,111,116,97,108,45,117,115,116,120,45,115,116,97,99,107,101,100,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,17"

/home/donp/projects/stacks/testnet-2.1/stx-wallet-cli/node_modules/@stacks/common/dist/utils.js:308
            throw new Error('Invalid byte sequence');
                  ^

Error: Invalid byte sequence
    at hexToBytes (/home/donp/projects/stacks/testnet-2.1/stx-wallet-cli/node_modules/@stacks/common/dist/utils.js:308:19)
    at Object.deserializeCV (/home/donp/projects/stacks/testnet-2.1/stx-wallet-cli/node_modules/@stacks/transactions/dist/clarity/deserialize.js:13:77)
    at decodeClarityValue (/home/donp/projects/stacks/testnet-2.1/stx-wallet-cli/stacks-node-cli:1080:21)
    at decodeCLI (/home/donp/projects/stacks/testnet-2.1/stx-wallet-cli/stacks-node-cli:1150:10)
    at main (/home/donp/projects/stacks/testnet-2.1/stx-wallet-cli/stacks-node-cli:1467:17)
    at Object.<anonymous> (/home/donp/projects/stacks/testnet-2.1/stx-wallet-cli/stacks-node-cli:1510:1)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)

Node.js v18.9.1
```
What is the right way to inspect the function call return value?

**Comment by jcnelson** [comment]
How are you generating the encoded `uint`?

```
$ ./stacks-node-cli encode uint 1
"0100000000000000000000000000000001"
$ ./wallet-cli contract-call -N "http://next.stacks.org:20443" -s - -f 123 -n 1 -v -A 1 ST000000000000000000002AMW42H.pox-2 get-total-ustx-stacked 0100000000000000000000000000000001 < ./test/test-seed-phrase.txt 
"0000000001040028897d13efb05f35297cdb548b23cbfe2d4f652a0000000000000000000000000000007b00009971c421b3e61b83ae2dbc38edd2110bad20c14165319cc5da58d2cbfc1605c86a0484966ce46dca0cd09d239c7ef39cf9aa0530aa56e0476f914c21fe7c7e36030200000000021a000000000000000000000000000000000000000005706f782d32166765742d746f74616c2d757374782d737461636b6564000000010100000000000000000000000000000001"
$ node --version
v16.17.1
```

**Comment by donpdonp** [comment]
both wallet-cli and stacks-node-cli are returning comma separated base10 numbers for me, instead of a hex string. 

```
 $ ./stacks-node-cli encode uint 1
"1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1"
```

Note sure why that is. the `stx-wallet-cli` repo is up to date with github. I tried downgrading node from v18 to v16 but still the same output.

**Comment by donpdonp** [comment]
the serialization fix is below. recently @stacks/common changed the return value of serialize() from Buffer which supports toString('hex') to Uint8Array which does not, but they provided their own helper function to convert to hex. 

```
-  transaction.serialize().toString('hex');
+  stx_common.bytesToHex(transaction.serialize());
```

Applying the change locally and re-running the call to `get-total-ustx-stacked 1` (reward cycle 1), it is reporting an odd error about clarity type 128.

```
donp@carbon stx-wallet-cli $ ./stacks-node-cli encode uint 1 
"0100000000000000000000000000000001"
donp@carbon stx-wallet-cli $ cat testnet.seed.txt|  ./wallet-cli contract-call -N "http://2-1-api.testnet.hiro.so" -s - -t -f 123 -n 1 -v -A 1  ST000000000000000000002AMW42H.pox-2 get-total-ustx-stacked "0100000000000000000000000000000001"
"80800000000400323657c42020e6964e27510f1899b2e0c6cf246b0000000000000000000000000000007b000157542c6b98693423bd39bcd2c4039b367f7f5ffbc34c7a8f226bb81c1ce85ede299ed0ed39c36e0920d930b8178035a45a3b9eed6f0d882f027373ed3bf36725030200000000021a000000000000000000000000000000000000000005706f782d32166765742d746f74616c2d757374782d737461636b6564000000010100000000000000000000000000000001"
donp@carbon stx-wallet-cli $ ./stacks-node-cli decode "80800000000400323657c42020e6964e27510f1899b2e0c6cf246b0000000000000000000000000000007b000157542c6b98693423bd39bcd2c4039b367f7f5ffbc34c7a8f226bb81c1ce85ede299ed0ed39c36e0920d930b8178035a45a3b9eed6f0d882f027373ed3bf36725030200000000021a000000000000000000000000000000000000000005706f782d32166765742d746f74616c2d757374782d737461636b6564000000010100000000000000000000000000000001"
/home/donp/projects/stacks/testnet-2.1/stx-wallet-cli/node_modules/@stacks/transactions/dist/clarity/deserialize.js:22
        throw new errors_1.DeserializationError(`Cannot recognize Clarity Type: ${n}`);
              ^

DeserializationError: Cannot recognize Clarity Type: 128
    at /home/donp/projects/stacks/testnet-2.1/stx-wallet-cli/node_modules/@stacks/transactions/dist/clarity/deserialize.js:22:15
    at BytesReader.readUInt8Enum (/home/donp/projects/stacks/testnet-2.1/stx-wallet-cli/node_modules/@stacks/transactions/dist/bytesReader.js:64:15)
    at Object.deserializeCV (/home/donp/projects/stacks/testnet-2.1/stx-wallet-cli/node_modules/@stacks/transactions/dist/clarity/deserialize.js:21:30)
    at decodeClarityValue (/home/donp/projects/stacks/testnet-2.1/stx-wallet-cli/stacks-node-cli:1080:21)
    at decodeCLI (/home/donp/projects/stacks/testnet-2.1/stx-wallet-cli/stacks-node-cli:1150:10)
    at main (/home/donp/projects/stacks/testnet-2.1/stx-wallet-cli/stacks-node-cli:1468:17)
    at Object.<anonymous> (/home/donp/projects/stacks/testnet-2.1/stx-wallet-cli/stacks-node-cli:1511:1)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
```

**Comment by donpdonp** [comment]
note to self: output is a serialized transaction, not a serialized clarity value.  

the original issue is fixed by using stx_common.bytesToHex(). closing.
